server:
  port: 9090

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


logging:
  level:
    org.springframework.web: ERROR
    dev.jmv.crypto: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  file:
    name: logs/app.log